services:
  homeassistant:
    container_name: ha-tankerkoenig-card-test
    image: homeassistant/home-assistant:stable
    volumes:
      - ./test/ha-config:/config
      - ./dist:/config/www/tankerkoenig-card:ro
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    ports:
      - '8129:8123'
